/**
 * TEMPORAIRE — courses de développement si la liste réelle est vide.
 */

import type { ActivityRide } from './activityTypes';

function todayAt(hours: number, minutes: number): string {
  const date = new Date();
  date.setHours(hours, minutes, 0, 0);
  return date.toISOString();
}

export const DEMO_ACTIVITY_RIDES: ActivityRide[] = [
  {
    id: 'demo-act-1',
    pickupLabel: 'UNIKIN',
    dropoffLabel: 'Gombe',
    pickupLat: -4.396,
    pickupLng: 15.309,
    dropoffLat: -4.305,
    dropoffLng: 15.303,
    occurredAt: todayAt(10, 35),
    driverName: 'Patrick Nzambe',
    vehicle: 'Toyota Corolla',
    plate: 'TNB 001',
    categoryId: 'comfort',
    fareCents: 1_850_000,
    estimated: false,
    status: 'completed',
    payment: 'Espèces',
    reference: 'TNB-20260915-001',
    distanceKm: 11.4,
  },
  {
    id: 'demo-act-2',
    pickupLabel: 'Limete',
    dropoffLabel: 'Aéroport de N’djili',
    pickupLat: -4.375,
    pickupLng: 15.345,
    dropoffLat: -4.3856,
    dropoffLng: 15.4446,
    occurredAt: '2026-09-14T16:20:00.000Z',
    driverName: 'Jean Mbala',
    vehicle: 'Hyundai Accent',
    plate: 'TNB 214',
    categoryId: 'economy',
    fareCents: 3_200_000,
    estimated: false,
    status: 'completed',
    payment: 'Espèces',
    reference: 'TNB-20260914-088',
    distanceKm: 18.2,
  },
  {
    id: 'demo-act-3',
    pickupLabel: 'Kintambo',
    dropoffLabel: 'Lingwala',
    pickupLat: -4.327,
    pickupLng: 15.27,
    dropoffLat: -4.318,
    dropoffLng: 15.3,
    occurredAt: '2026-09-13T09:10:00.000Z',
    driverName: 'Grâce Ilunga',
    vehicle: 'Moto Haojue',
    plate: 'TNB M12',
    categoryId: 'moto',
    fareCents: 800_000,
    estimated: false,
    status: 'completed',
    payment: 'Espèces',
    reference: 'TNB-20260913-044',
    distanceKm: 6.1,
  },
  {
    id: 'demo-act-4',
    pickupLabel: 'Mont-Ngafula',
    dropoffLabel: 'Gombe',
    pickupLat: -4.43,
    pickupLng: 15.29,
    dropoffLat: -4.305,
    dropoffLng: 15.303,
    occurredAt: '2026-09-16T07:30:00.000Z',
    driverName: null,
    vehicle: null,
    plate: null,
    categoryId: 'economy',
    fareCents: 2_150_000,
    estimated: true,
    status: 'scheduled',
    payment: 'Espèces',
    reference: 'TNB-20260916-007',
    distanceKm: 19.5,
  },
  {
    id: 'demo-act-5',
    pickupLabel: 'Bandalungwa',
    dropoffLabel: 'Ngaliema',
    pickupLat: -4.35,
    pickupLng: 15.28,
    dropoffLat: -4.327,
    dropoffLng: 15.249,
    occurredAt: '2026-09-10T18:45:00.000Z',
    driverName: null,
    vehicle: null,
    plate: null,
    categoryId: 'comfort',
    fareCents: 1_500_000,
    estimated: false,
    status: 'cancelled',
    payment: 'Espèces',
    reference: 'TNB-20260910-119',
    distanceKm: 8.4,
  },
];

export const DEMO_ACTIVITY_FALLBACK_STATS = {
  trips: 12,
  spendCents: 8_950_000,
  distanceKm: 74,
} as const;
